"""
Playwright tests — generated by Agentic SDLC pipeline. Do not edit manually.
"""
import pytest

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_add_to_cart_updates_counter_instantly(page):
    """SC-001: Add to cart updates counter instantly."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("load", timeout=30000)
    page.locator(".product-thumb").first.hover()
    page.wait_for_timeout(500)
    page.locator("button.btn-cart:visible").first.click(force=True)
    page.wait_for_timeout(2000)
    badge = page.locator(".cart-item-total")
    assert badge.count() > 0 and badge.first.inner_text().strip() != "0", "Cart counter not updated"

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_cart_dropdown_shows_item_names_and_prices(page):
    """SC-002: Cart dropdown shows item names and prices."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("load", timeout=30000)
    page.locator(".product-thumb").first.hover()
    page.wait_for_timeout(500)
    page.locator("button.btn-cart:visible").first.click(force=True)
    page.wait_for_timeout(2000)
    page.locator("a.cart[href='#cart-total-drawer']").click()
    page.wait_for_timeout(1000)
    drawer = page.locator("#cart-total-drawer")
    assert drawer.is_visible(), "Cart drawer did not open"
    assert drawer.locator("a").count() > 0, "Cart drawer shows no item links"

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_remove_item_recalculates_cart_total(page):
    """SC-003: Remove item recalculates cart total."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("load", timeout=30000)
    page.locator(".product-thumb").first.hover()
    page.wait_for_timeout(500)
    page.locator("button.btn-cart:visible").first.click(force=True)
    page.wait_for_timeout(2000)
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=checkout/cart")
    page.wait_for_load_state("load", timeout=20000)
    remove = page.locator("button.btn-danger").first
    if remove.count() > 0:
        remove.click(force=True)
        page.wait_for_timeout(1500)
    assert page.locator("#content").count() > 0, "Cart page not visible"

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_search_returns_relevant_product_results(page):
    """SC-004: Search returns relevant product results."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    search = page.locator("input[name='search']").first
    search.wait_for(timeout=15000)
    search.fill("iPhone")
    search.press("Enter")
    page.wait_for_load_state("domcontentloaded")
    assert page.locator(".product-thumb").count() > 0, "No search results"

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_catalog_displays_product_tiles_with_pricing(page):
    """SC-005: Catalog displays product tiles with pricing."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=18")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    assert page.locator(".product-thumb").first.is_visible(), "No product tiles"

@pytest.mark.scenario("SC-006")
@pytest.mark.requirement("AC-006")
def test_sc_006_product_tile_opens_detail_page_with_name_image_pri(page):
    """SC-006: Product tile opens detail page with name, image, price."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    assert page.locator("h1").first.inner_text().strip() != ""
    assert page.locator(".price-new, .price, h2.price").count() > 0

@pytest.mark.scenario("SC-007")
@pytest.mark.requirement("AC-007")
def test_sc_007_category_filter_narrows_product_list(page):
    """SC-007: Category filter narrows product list."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=25")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    filter_link = page.locator(".filter-manufacturer a").filter(has_text="Apple")
    if filter_link.count() == 0:
        filter_link = page.locator("#column-left a").filter(has_text="Apple")
    if filter_link.count() > 0:
        filter_link.first.click()
        page.wait_for_load_state("domcontentloaded", timeout=15000)
    assert page.locator("#content").count() > 0, "Content not visible after filter"

@pytest.mark.scenario("SC-008")
@pytest.mark.requirement("AC-008")
def test_sc_008_success_message_appears_on_cart_add(page):
    """SC-008: Success message appears on cart add."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("load", timeout=30000)
    page.locator(".product-thumb").first.hover()
    page.wait_for_timeout(500)
    page.locator("button.btn-cart:visible").first.click(force=True)
    # Toast is transient — wait for it to appear (up to 3s) rather than a fixed 2s sleep
    success = page.locator("p.m-0.font-size-sm, .alert-success, .toast-body")
    success.first.wait_for(state="visible", timeout=3000)
    assert success.count() > 0, "No success notification after adding to cart"
